config/routes.rb
 Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'event_tickets_api/create'

  # get 'event_tickets_api/update'

  root 		'application#root'
  # 'sessions#new'
  
  get '/help', to: 'gor_main#help'
  get '/contact', to: 'gor_main#contact'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/soundcloud/connect' => 'soundcloud#connect'

  get '/soundcloud/callback' => 'soundcloud#connected'

  get '/logout', to: 'soundcloud#destroy'

  # get '/sessions/:page' => "sessions#show"
  get '/edit', to: 'users#edit'

  # get '/soundcloud/oauth-callback', to: 'sessions#omniauth_create'


   resources :users, except: [:index] do
   	resources :wardrobes
   	resources :playlist, except: [:index, :show]
   end

   resource :playlist do
   	member do
	   	patch 'change_up' #Randomize what gets played while keeping kept_songs in the playlist
	end

   	resources :songs, except: [:edit, :update] do
   		member do
   			post 'keep_song'
   		end
   	end
   end

  resources :preferences, only: [:index, :create, :destroy]

  resources :wardrobes, only: [:update, :index, :destroy, :detail]

  resources :gor_clothing, except: [:new] do
  	member do
  		resources :images, only: [:index, :show, :preview]
  	end
  end

  resources :possible_matches, only: [:show, :detail] do
  	member do
  		get :visible_gor_clothing, to: :show
  	end
  end

  get ':performer_name', to: 'event_tickets#artist_events', as: :artist_events

  resources :event_tickets, only: [:index, :show] do
  	 collection do
  	 	get ':input' => 'event_tickets#search', as: :search
  	 end
  end

  namespace :admin do

  	resources :gor_clothing, except: [:show] do
  		post :preview, on: :new
  		member do
  			get '/', to: :detail
  			resources :possible_matches do
  				match :destroy, to: 'possible_matches#destroy', via: [:delete], on: :collection
  			end
  			resources :images, except: [:edit, :update] do
  				match :edit_some, to: 'images#edit_some', via: [:get], on: :collection
  				match :destroy, to: 'images#destroy', via: [:delete], on: :collection
  				get :preview, on: :new
  			end
  		end
  	end

  	#image upload --> new --> triggered by carrier_wave uploader--> preview action --> render admin_gor_clothing_image_path alert(is show picture ok?)
  	#save image --> create --> 
  	

  	resources :users do
  		get 'saved_wardrobes'
  		member do
			resources :playlists, only: [:create, :destroy, :show, :index]
  		end
	end

  end


end

app/models/possible_match.rb
class PossibleMatch < ActiveRecord::Base
	belongs_to :suggested_piece, class_name: 'Gor_Clothing'
	belongs_to :contemplated_piece, class_name: 'Gor_Clothing'
	validates :suggested_piece_id, presence: true
	validates :contemplated_piece_id, presence: true

	has_one :image
	validates_associated :image

	validates_uniqueness_of :image, conditions: -> {where(type_of_image: 'show_picture')}
	# accepts_nested_parameters_for :image, reject_if: proc {|attributes| attributes[:type_of_image] != :show_picture !! :front_shot}
	private

	
		def next_suggested_male
	  		Gor_Clothing.where("gor_clothings.id >= ? AND gor_clothing.gender = ?", gor_clothing.first.id, male).order("gor_clothings.id ASC")
		end

		def previous_suggested_male
			Gor_Clothing.where("gor_clothings.id <= ? AND gor_clothing.gender = ?", gor_clothing.last.id, male).order("gor_clothings.id DESC")
		end

		def next_suggested_female
			Gor_Clothing.where("gor_clothings.id >= ? AND gor_clothing.gender = ?", gor_clothing.first.id, female).order("gor_clothings.id ASC")
		end

		def previous_suggested_female
		 	Gor_Clothing.where("gor_clothings.id <= ? AND gor_clothing.gender = ?", gor_clothing.last.id, female).order("gor_clothings.id DESC")
		end
	
end

app/controllers/api/v1/possible_matches_controller.rb
class PossibleMatchesController < VisibleGorClothingController
	before_action :admin, only: [:new, :create, :edit, :destroy]
	respond_to :js, :html

	before_action :setup_possible_matches, only: [:show, :organize_piecesz]
	

	def new
		@gor_clothings = Gor_Clothing.all
		@possible_match = PossibleMatch.new(contemplated_piece_id: params[:gor_clothing_id])
	end

	def create 
		@possible_match = PossibleMatch.create(possible_matches_params)
		flash[:notice] = "Possible matches for this gor_clothing piece created" if @possible_matches.save
	end

	def show

		respond_to do |format|
			format.html {}
			format.js
		end	
	end

	def index
	end
	
	def edit
		@gor_clothing = Gor_Clothing.find(params[:contemplated_piece_id])
		@possible_matches = @gor_clothing.suggested_pieces(:all)
	end

	def update
	end

	def destroy
		@possible_matches_selected = PossibleMatch.where(:suggested_pieces => params[:collateral_images]) #identify which images have setForDeletion
		if @possible_matches_selected.destroy
			flash[:notice] = "Selected possible matches destroyed"
		end
	end
	
	private
	
		def setup_possible_matches
			
			 if current_user.gender == :male #We need to specify merch_type: :top for Gor_Clothing and merch_type? for PossibleMatches
                       		@contemplated_piece = self.fetch(params[:visible_gor_clothing][:contemplated_piece_id], Gor_Clothing.order(gender: :male, created_at: :desc).first)
                       		@standalone_bottoms = Gor_Clothing.where('standalone = ?', true).where('merch_type = ?', bottom).order(gender: :male, created_at: :desc)
                        	@standalone_tops = Gor_Clothing.where('standalone = ?', true).where('merch_type = ?', top).order(gender: :male, created_at: :desc)
                        	@suggested_tops = Gor_Clothing.where('merch_type = ?', top).where('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).order(gender: :male, created_at: :desc)
                       		@suggested_bottoms = Gor_Clothing.where('merch_type = ?', bottom).where('toggled_pieces.contemplated_piece = ?', @contemplated_piece.id).order(gender: :male, created_at: :desc)
                        	@extra_tops = Gor_Clothing.where('merch_type = ?', top).where.not('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).where('standalone = ?', false).order(created_at: :desc)
                        	@extra_bottoms = Gor_Clothing.where('merch_type = ?', bottom).where.not('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).where('standalone = ?', false).order(created_at: :desc)
                	elsif current_user.gender == :female
                        	@contemplated_piece = self.fetch(params[:visible_gor_clothing][:contemplated_piece_id], Gor_Clothing.order(gender: :female, created_at: :desc).first)
                        	@standalone_tops = Gor_Clothing.where('standalone = ?', true).where('merch_type = ?', top).order(gender: :female, created_at: :desc)
                                @standalone_bottoms = Gor_Clothing.where('standalone = ?', true).where('merch_type = ?', bottom).order(gender: :female, created_at: :desc)
                        	@suggested_tops = Gor_Clothing.where('merch_type = ?', top).where('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).order(gender: :female, created_at: :desc)
                        	@suggested_bottoms = Gor_Clothing.where('merch_type = ?', bottom).where('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).order(gender: :female, created_at: :desc)
                        	@extra_tops = Gor_Clothing.where('merch_type = ?', top).where.not('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).where('standalone = ?', false).order(created_at: :desc)
                        	@extra_bottoms = Gor_Clothing.where('merch_type = ?', bottom).where.not('toggled_pieces.contemplated_piece_id = ?', @contemplated_piece.id).where('standalone = ?', false).order(created_at: :desc)
                	end
	
		end	
	
		def addtoArray(arraylist, declaredArray)
                    for i in arraylist.length - 1
                        declaredArray += arraylist[i]
                    end
                end
			
		def organize_pieces
		         LowerComponents = new Array
			 UpperComponents = new Array
		if (@contemplated_piece.merch_type == 'bottom')
                        addToArray(@contemplated_piece, LowerComponents);
                        addToArray(@extra_bottoms, LowerComponents);
                        addToArray(@standalone_bottoms, LowerComponents);
                        addToArray(@suggested_tops, UpperComponents);
                        addToArray(@extra_tops, UpperComponents);
                        addToArray(@standalone_tops, UpperComponents);
                        return [LowerComponents, UpperComponents];
                else if (@contemplated_piece.merch_type == 'top')
                        addToArray(@contemplated_piece, UpperComponents);
                        addToArray(@extra_tops, UpperComponents);
                        addToArray(@standalone_tops, UpperComponents);
                        addToArray(@suggested_bottoms, LowerComponents);
                        addToArray(@extra_bottoms, LowerComponents);
                        addToArray(@standalone_bottoms, LowerComponents);
                        return [UpperComponents, LowerComponents];
		else 
			return;
	        end
		
		def possible_matches_params	
			params.require(PossibleMatch).permit(:contemplated_piece_id, :suggested_piece_id, :gor_clothing_id, images_attributes: [:picture])
		end

end

app/helpers/possible_matches_helper.rb
module PossibleMatchesHelper

end

app/views/possible_matches/_destroy.html.erb
<i class="icon-destroy-link" remote: true></i>

app/views/possible_matches/_finish_edit.html.erb
<%= link_to 'Finish Editing', admin_possible_matches_path(@gor_clothing), :remote => true, :data => {confirm => "Are you sure you want to delete these?"}, id: 'finish_edit_matches' %>

app/views/possible_matches/_index.html.erb
<% content_for :head do %>
     <%= javascript_include_tag 'admin/admin' %>
     <%= javascript_include_tag 'prototype' %>
     <%= javascript_include_tag 'scriptaculous' %>
<%end%>
<div class = "detail_possible_matches">
	<div class = "validation-error"></div>
	<h2>Possible Matches</h2> | 
	<span class="subtle">
		<%= link_to "Edit", possible_matches_edit_admin_gor_clothing_path(@gor_clothing), remote: true, id: 'edit_possible_matches' %>
	</span>
	<span id= 'Finish'></span>
	<% for suggested_piece in @gor_clothing.suggested_pieces %>
	<div class = "possible_match">
		<span id="possible_match_<%= suggested_piece.id %>">
			<a 'href=?', suggested_piece_id>
				<%= image_tag suggested_piece.image.picture.url %>
			</a>
		</span>
	</div>
	<%end%>
</div>

app/views/possible_matches/_possible_matches_contemplated_piece.html.erb
<li id='currently_contemplated' class='contemplated_piece_<%=@contemplated_piece.id%>' class =  'possible_pieces' focus-image>
	 <%= link_to(content_tag(:a, "", remote: true, controller: PossibleMatches, action: "show", id: @visible_gor_clothing.contemplated_piece_id, onclick = "return false;"), image_tag(ng_src = "{{contemplated_piece.image}}"), controller: Gor_Clothing, action: "detail", id: @contemplated_piece.id)%>
	 <details ng-bind-html = 'renderHtml(contemplated_piece.price)' class = 'contemplated_piece_price'></details>
	 <details ng-bind-html = 'renderHtml(contemplated_piece.description)' class = 'contemplated_piece_description'></details>
</li>
 

app/views/possible_matches/_possible_matches_extra_tops.html.erb
<span ng-switch = 'top.id'>
	<% for gor_clothing in @possible_match_extra_tops %>
		<span ng-switch-when = '{{top.id}}'>
			<li id = 'currently_visible_extra_top' class='non_suggested_top_<%= gor_clothing.id%>' class = 'possible_pieces' focus-image ng-class = "{'toLeft': toLeft, 'toRight': toRight}">
				<%= link_to(content_tag(:a, '', remote: true, controller: PossibleMatches, action: "show", id: @visible_gor_clothing.contemplated_piece, onclick = "return false;"), image_tag(ng-src = "{{topInPlay.image}}"), controller: Gor_Clothing, action: "detail", id: gor_clothing.id%> 
				<details ng-bind-html = 'renderHtml(topInPlay.price)' class = 'piece_price'></details>
				<details ng-bind-html = 'renderHtml(topInPlay.description)' class = 'piece_description'></details>
			</li>
		</span>
	<%end%>
</span>

app/views/possible_matches/_possible_matches_suggested_bottoms.html.erb
<span ng-switch = 'suggested_piece.id'>
	<span ng-switch-when = '{{suggested_piece.id}}'>
		<% for suggested_piece in @possible_match_suggested_bottoms %>
			<li id = 'currently_visible_bottom' class = 'suggested_bottom_<%= suggested_piece.id%>' class = 'possible_pieces' focus-image ng-class = "{'toLeft': toLeft, 'toRight': toRight}">
			<%= link_to(content_tag(:a, '', remote: true, controller: PossibleMatches, action: "show", id: @visible_gor_clothing.contemplated_piece_id, onclick = "return false;"), image_tag(ng-src = "{{bottomInPlay.image}}"), controller: Gor_Clothing, action: "detail", id: suggested_piece.id %>
				<details ng-bind-html = 'renderHtml(bottomInPlay.price)' class = 'piece_price'></details>
				<details ng-bind-html = 'renderHtml(bottomInPlay.description)' class = 'piece_description'></details>
			</li>
		<%end%>
	</span>
</span>

app/views/possible_matches/_possible_matches_suggested_tops.html.erb
<span ng-switch = 'suggested_piece.id'>
	<span ng-switch-when = '{{suggested_piece.id}}'>
		<% for suggested_piece in @possible_match_suggested_tops %>
			<li id = 'currently_visible_top' class = 'suggested_top_<%= suggested_piece.id%>' class = 'possible_pieces' focus-image ng-class = "{'toLeft': toLeft, 'toRight': toRight}">
				<%= link_to(content_tag(:a, '', remote: true, controller: PossibleMatches, action: "show", id: @visible_gor_clothing.contemplated_piece, onclick = "return false;"),
					image_tag(ng-src = "{{topInPlay.image}}"), controller: Gor_Clothing, action: "detail", id: suggested_piece.id %>
				<details ng-bind-html = 'renderHtml(topInPlay.price)' class = 'piece_price'></details>
				<details ng-bind-html = 'renderHtml(topInPlay.price)' class = 'piece_description'></details>
			</li>
		<%end%>
	</span>
</span>

app/views/possible_matches/_possible_pieces_standalone_bottoms.html.erb
<span ng-switch = 'bottom.id'>
	<% for gor_clothing in @gor_clothing_standalone_bottoms %>
		<span ng-switch-when = '{{bottom.id}}'>
			<li id = 'currently_visible_standalone_bottom' class='standalone_bottoms_<%= gor_clothing.id%>' class = 'possible_pieces' focus-image ng-class = "{'toLeft': toLeft, 'toRight': toRight}">
				<%= link_to(content_tag(:a, '', remote: true, controller: PossibleMatches, action: "show", id: @visible_gor_clothing.contemplated_piece, onclick = "return false;"), image_tag(ng_src = "{{bottomInPlay.image}}"), controller: Gor_Clothing, action: "detail", id: gor_clothing.id%>
				<details ng-bind-html = 'renderHtml(bottomInPlay.price)' class = 'standalone_piece_price'></details>
				<details ng-bind-html = 'renderHtml(bottomInPlay.description)' class = 'standalone_piece_description'></details>
			</li>
		</span>
	<%end%>
</span>

app/views/possible_matches/_possible_pieces_standalone_tops.html.erb
<span ng-switch = 'top.id'>
	<% for gor_clothing in @gor_clothing_standalone_tops %>
		<span ng-switch-when = '{{top.id}}'>
			<li id = 'currently_visible_standalone_tops' class='standalone_tops_<%= gor_clothing.id%>' class = 'possible_pieces' focus-image ng-class = "{'toLeft': toLeft, 'toRight': toRight}">
				<%= link_to image_tag(ng_src = "{{topInPlay.image}}"), controller: Gor_Clothing, action: "detail", id: gor_clothing.id%>
				<details ng-bind-html = 'renderHtml(topInPlay.price)' class = 'standalone_piece_price'></details>ng-class = "{'toLeft': toLeft, 'toRight': toRight}"
				<details ng-bind-html = 'renderHtml(topInPlay.description)' class = 'standalone_piece_description'></details>
			</li>
		</span>
	<%end%>
</span>

app/views/possible_matches/_potential_piece.html.erb
<%= form_for([:admin, @possible_match], remote: true, url: {action: 'create'}, html: {id: 'potential_piece_<%= potential_piece_id %>'} do |f| %>
	<div class = 'buttons' >
		<%= f.radio_button 'possible_match', 'suggested_piece', 'potential_piece' %>
		<%= f.label :possible_match, :suggested_piece, 'Potential Piece', :value => 'potential_piece' %>
		<%= f.radio_button 'possible_match', 'suggested_piece', 'false' %>
		<%= f.label :possible_match, :suggested_piece, 'Next', :value => 'false' %>
	</div>
	<span class = "content">
	    <%= image_tag @possible_match.image.picture.url if @possible_match.image? %>
	</span>
	<span class = 'potential_piece_pic'>
		<%= image_tag potential_piece.image.picture.url if potential_piece.image? %>
	</span>
	<%= f.submit 'Finished' %>
<%end%>

app/views/possible_matches/edit.js.erb
$finish = $('#Finish');
$finish_edit = $('#finish_edit_matches');

$(document).ready(function(){
	append_destroy_links('#edit_possible_matches', '#possible_matches');
	if ($finish.html('')){
		$finish.html(" | " + "<%= escape_javascript(render('possible_matches/_finish_edit')) %>");
	}
	else {
		$finish.remove();
	}
	$('i.icon-destroy-link').on('click', function(e){
		$(this).addClass('set-for-deletion');
	});

	$finish_edit.on('click', deleteGORPossMatchesSetForDeletion, function(){
		$finish.html('');
	});
});

	

var deleteGORPossMatchesSetForDeletion = function(){
	$.ajax(beforeSend: function(xhr, settings) {
    		if ( settings.dataType == undefined ) {
        			xhr.setRequestHeader("*/*;q=0.5, text/javascript", "application/javascript");
    		}
    			return fire(element, 'ajax:beforeSend', xhr);
		},{
		type: 'DELETE',
		url: 'admin/gor_clothing/:id/possible_matches',
		data: {
			destroy_link_icons: document.getElementsByClassName('icon-destroy-link'),
			collateral_images: $('i.set-for-deletion').siblings('#possible_match_<%= suggested_piece.id %>'),
			collateral_images_parent: $('.collateral_images').has('i').hasClass('set-for-deletion') //All Elements with ClassName collateral-images and set-for-deletion
		},
		context: collateral_images_parent,
		success: function(evt, data, status, xhr){
				 new Effect.Parallel([
    					new Effect.Move($(this), { sync: true, x: 400, y: 0, mode: 'relative' }),
    					new Effect.Opacity($(this), { sync: true, from: 1, to: 0 })
  				],{ 
    					duration: 1.5
				});
					$(this).remove();
		}
	});
};

app/views/possible_matches/new.js.erb
// var FormEl = $('potential_piece_<%= potential_piece_id %>');
var el = $('.potential_piece_pic');
var FormEl = $('.potential_piece_box');

previewFile('PossibleMatchNew');

<%= render(:partial => 'potential_piece', :collection => @gor_clothings) || 'There are no potential pieces that can evaluated.' %>

<% @gor_clothings.each do |potential_piece| %>

FormEl.html('');

FormEl.html("<%= escape_javascript(render('potential_piece'))%>");

<% if potential_piece.attribute_present(:suggested_piece) %>
	<% next %>
<%end%>

<%end%>

app/views/possible_matches/possible_matches.js.erb
$finish = $('#Finish');

$(document).ready(function(){
	$('#edit_possible_matches').on('click', function(e){
				append_destroy_links('#edit_possible_matches', '#possible_matches');
				if ($finish.html('')){
					$finish.html(" | " + "<%= escape_javascript(render('possible_matches/_finish_edit')) %>");
				}
				else {
					$finish.remove();
				}
	});

	$('i.icon-destroy-link').on('click', function(e){
		$(this).addClass('set-for-deletion');
	});
});

var deleteGORPossMatchesSetForDeletion = function(){
	$.ajax(beforeSend: function(xhr, settings) {
    		if ( settings.dataType == undefined ) {
        			xhr.setRequestHeader("*/*;q=0.5, text/javascript", "application/javascript");
    		}
    			return fire(element, 'ajax:beforeSend', xhr);
		},{
		type: 'DELETE',
		url: '/admin/gor_clothing/:id/possible_matches',
		data: {
			destroy_link_icons: document.getElementsByClassName('icon-destroy-link'),
			collateral_images: $('i.set-for-deletion').siblings('#possible_match_<%= suggested_piece.id %>'),
			collateral_images_parent: $('.collateral_images').has('i').hasClass('set-for-deletion') //All Elements with ClassName collateral-images and set-for-deletion
		},
		context: collateral_images_parent,
		success: function(evt, data, status, xhr){
				 new Effect.Parallel([
    					new Effect.Move($(this), { sync: true, x: 400, y: 0, mode: 'relative' }),
    					new Effect.Opacity($(this), { sync: true, from: 1, to: 0 })
  				],{ 
    					duration: 1.5
				});
					$(this).remove();
		}
	});
};