config/routes.rb
 Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'event_tickets_api/create'

  # get 'event_tickets_api/update'

  root 		'application#root'
  # 'sessions#new'
  
  get '/help', to: 'gor_main#help'
  get '/contact', to: 'gor_main#contact'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/soundcloud/connect' => 'soundcloud#connect'

  get '/soundcloud/callback' => 'soundcloud#connected'

  get '/logout', to: 'soundcloud#destroy'

  # get '/sessions/:page' => "sessions#show"
  get '/edit', to: 'users#edit'

  # get '/soundcloud/oauth-callback', to: 'sessions#omniauth_create'


   resources :users, except: [:index] do
   	resources :wardrobes
   	resources :playlist, except: [:index, :show]
   end

   resource :playlist do
   	member do
	   	patch 'change_up' #Randomize what gets played while keeping kept_songs in the playlist
	end

   	resources :songs, except: [:edit, :update] do
   		member do
   			post 'keep_song'
   		end
   	end
   end

  resources :preferences, only: [:index, :create, :destroy]

  resources :wardrobes, only: [:update, :index, :destroy, :detail]

  resources :gor_clothing, except: [:new] do
  	member do
  		resources :images, only: [:index, :show, :preview]
  	end
  end

  resources :possible_matches, only: [:show, :detail] do
  	member do
  		get :visible_gor_clothing, to: :show
  	end
  end

  get ':performer_name', to: 'event_tickets#artist_events', as: :artist_events

  resources :event_tickets, only: [:index, :show] do
  	 collection do
  	 	get ':input' => 'event_tickets#search', as: :search
  	 end
  end

  namespace :admin do

  	resources :gor_clothing, except: [:show] do
  		post :preview, on: :new
  		member do
  			get '/', to: :detail
  			resources :possible_matches do
  				match :destroy, to: 'possible_matches#destroy', via: [:delete], on: :collection
  			end
  			resources :images, except: [:edit, :update] do
  				match :edit_some, to: 'images#edit_some', via: [:get], on: :collection
  				match :destroy, to: 'images#destroy', via: [:delete], on: :collection
  				get :preview, on: :new
  			end
  		end
  	end

  	#image upload --> new --> triggered by carrier_wave uploader--> preview action --> render admin_gor_clothing_image_path alert(is show picture ok?)
  	#save image --> create --> 
  	

  	resources :users do
  		get 'saved_wardrobes'
  		member do
			resources :playlists, only: [:create, :destroy, :show, :index]
  		end
	end

  end


end

app/models/gor_clothing.rb
class GorClothing < ActiveRecord::Base
	enum purchase_status: [:on_shelf, :purchased]
	enum status: [:unfavorited, :favorited]
	has_attached_file :image, :styles => {large: "90x90>", medium: "70x70>", thumb: "45x45#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	
	VALID_PRICE_REGEX = /\$?\d*\.?\d+/

	belongs_to :user
	belongs_to :wardrobe

	validates :quantity, presence: true, numericality: {only_integer: true}
	validates :sizes, presence: true, inclusion: {in: %w(S M L)}
	validates :gender, presence: true, inclusion: {in: %w(male female androgynous)}
	validates :price, format: {with: VALID_PRICE_REGEX}
	validates :description, presence: true
	validates :colors_available, presence: true
	validates :merch_type, presence: true, inclusion: {in: %w(top bottom)}
	validates :standalone, presence: true
	# validates :possible_matches, inclusion: {} allow_blank: true
	
	has_many :static_pieces, class_name: 'PossibleMatch',
				    foreign_key: :suggested_piece_id,
				    dependent: :destroy

	has_many :toggled_pieces, class_name: 'PossibleMatch',
			  	       foreign_key: :contemplated_piece_id,
			  	       dependent: :destroy

	has_many :suggested_pieces, through: :static_pieces, source: :suggested_piece
	has_one :contemplated_piece, through: :toggled_pieces

	has_many :images
	validates_associated :image
	validates_presence_of :image
	validates_uniqueness_of :image, scope: [:type_of_image]
	accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc {|attributes| attributes[:type_of_image] != :first_shot || :back_shot || :model_shot}
	# :show_picture ||
	private

		def next_male
  			Gor_Clothing.where("gor_clothings.id > ? AND gor_clothings.gender = ?", self.id, male).order("gor_clothings.id ASC")
		end

		def previous_male
 			Gor_Clothing.where("gor_clothings.id < ? AND gor_clothings.gender = ?", self.id, male).order("gor_clothings.id DESC")
		end

		def next_female
			Gor_Clothing.where("gor_clothings.id > ? AND gor_clothings.gender = ?", self.id, female).order("gor_clothings.id ASC")
		end

		def previous_female
		 	Gor_Clothing.where("gor_clothings.id < ? AND gor_clothings.gender = ?", self.id, female).order("gor_clothings.id DESC")
		end

		def self.add_color(color)
			
		end

end

app/controllers/api/v1/gor_clothing_controller.rb
class GorClothingController < ApplicationController
	before_action :logged_in_user
	before_action :admin, only: [:update, :edit, :new, :create, :destroy]
	before_action :find_clothing, only: [:index, :show, :edit, :update, :destroy, :detail]
	respond_to :html, :js
	
	def index
	     @gor_clothings = Gor_Clothing.all
		if current_user.gender == :female
			@gor_clothing_next = @gor_clothing.next_female
			@gor_clothing_previous = @gor_clothing.previous_female
		elsif current_user.gender == :male
			@gor_clothing_next = @gor_clothing.next_male
			@gor_clothing_previous = @gor_clothing.previous_male
		end
		respond_with(@gor_clothings, :location => admin_gor_clothing_index_path)
	end

	def show #js Show details Price and Description
	end

	def new
	     @gor_clothing = Gor_Clothing.new
	end

	def create
	 	@gor_clothing = Gor_Clothing.new(gor_clothing_params)
	          if @gor_clothing.new_record?
		 	if @gor_clothing.save
		 		redirect_to new_admin_possible_match_path
		 	elsif @gor_clothing.images_attributes.invalid?
		 		image_preview
		 	else
		 		render 'new'
		 	end

		elsif @gor_clothing.persisted?
	 		if @gor_clothing.create(:images_attributes => {'type_of_image' => params[:type_of_image],
	 				  'picture' => params[:picture]})
	 			redirect_to detail_admin_gor_clothing_path(@gor_clothing)
	 		else
	 			image_preview
	 		end
		end		
	end


	def edit
	end

	def update
		if @gor_clothing.update(gor_clothing_params)
			flash[:success] = "Successful upload"
			redirect_to admin_gor_clothing_index_path
		else
			render 'edit'
		end
	end

	def destroy
		@gor_clothing.destroy!

		redirect_to admin_gor_clothing_index_path
	end


	private

		def gor_clothing_params
		    params.require(:Gor_Clothing).permit(:price, :description, :quantity, :gender, :size, images_attributes: [:picture])
		end	

end

app/helpers/gor_clothing_helper.rb
module GorClothingHelper

	def image_preview
		render 'images/new_preview' unless @gor_clothing.errors.count > 0 #render layout
	end

	def find_clothing
		@gor_clothing = Gor_Clothing.find(params[:gor_clothing_id])
	end

end

app/views/gor_clothing/_detail.html.erb
<div class = 'detail_images'><%= render 'images/_index' %></div>
<div class = 'description'>
	<h6 class = 'cloth_name'><%= @gor_clothing.name %></h6>
	<span class = 'description'><%= @gor_clothing.description %></span>
	<span class = 'price'><%= @gor_clothing.price %></span>
	<span class = 'size'><%= @gor_clothing.size %></span>
	<span class = 'colors_available'><%= @gor_clothing.colors_available %></span>
</div>
<div class = 'gor_clothing_update'>
	<%= link_to 'Edit', edit_admin_gor_clothing_path(@gor_clothing), remote: true, id: 'edit_piece' %> |
	<%= link_to 'New Piece', new_admin_gor_clothing_path, remote: true, id: 'new_piece' %> |
	<%= link_to 'Delete', admin_gor_clothing_path(@gor_clothing), method: :delete, remote: true, id: 'destroy_gor_clothing' %>
</div>
<div class = 'possible_matches'>
	<%= render 'possible_matches/index' %>
</div>

app/views/gor_clothing/_gor_detail.html.erb
<div class = 'detail_images'><%= render 'images/_index' %></div>
<div class = 'description'>
	<h6 class = 'cloth_name'><%= @gor_clothing.name %></h6>
	<span class = 'description'><%= @gor_clothing.description %></span>
	<span class = 'price'><%= @gor_clothing.price %></span>
	<span class = 'size'><%= @gor_clothing.size %></span>
	<span class = 'colors_available'><%= @gor_clothing.colors_available %></span>
</div>
<div class = 'gor_clothing_update'>
	<%= link_to 'Edit', edit_admin_gor_clothing_path(@gor_clothing), remote: true, id: 'edit_piece' %> |
	<%= link_to 'New Piece', new_admin_gor_clothing_path, remote: true, id: 'new_piece' %> |
	<%= link_to 'Delete', admin_gor_clothing_path(@gor_clothing), method: :delete, remote: true, id: 'destroy_gor_clothing' %>
</div>
<div class = 'possible_matches'>
	<%= render 'possible_matches/index' %>
</div>

app/views/gor_clothing/_new_piece.html.erb
<%= form_for @GorClothing, html: {multipart: true} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class = "field" >
	<%= f.label :name %>
	<%= f.text_field :name %>
    <div>
    <div class = "field">
	<%= f.label :description %>
	<%= f.text_area :description %>
    </div>
    <div class = "field">
	<%= f.label :quantity %>
	<%= f.text_field :quantity%>
    </div>
    <div class = "field">
	<%= f.label :price %>
	<%= f.text_field :price%>
    </div>
    <div class = "field">
	<%= f.label :gender %>
	<%= f.select(:gender, options_for_select([['M', male]['F', female]['A', androgynous]])) %>
    </div>
    <div class = "field">
	<%= f.label :size %>
	<%= f.select(:size, options_for_select([['S', small]['M', medium]['L', large]])) %>
    </div>
    <%= f.fields_for :image do |i| %>
	<span class = "picture">
		<%= i.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
	</span>
    <%end%>
<%end%>

app/views/gor_clothing/destroy.js.erb
var nav = $('.merchandise_nav');
var el = $('#main-content');

<% if @gor_clothing_next.any? %>
	el.html("<%= @gor_clothing_next.limit(1) %>");
<%else%>
	nav.find('#next_piece').val('');
	el.html("<%= @gor_clothing_previous.limit(1) %>");
<%end%>

app/views/gor_clothing/detail.js.erb
var el = $('#main-content');
var possible_matches = $('.detail_possible_matches');

el.html('');
el.html("<%= escape_javascript(render('gor_clothing/gor_detail'))%>");

<% if @gor_clothing.contemplated_piece? && @gor_clothing.suggested_pieces.any? %>
	possible_matches.html("<%= escape_javascript(render('possible_matches/index'))%>");
<%else%>
	possible_matches.html('');
<%end%>

app/views/gor_clothing/edit.html.erb
<% provide(:title, "Edit Merch") %>
<h1>Update Merch</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@GorClothing) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
      
      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :quantity %>
      <%= f.text_field :quantity, class: 'form-control' %>

      <%= f.label :size, "Confirmation" %>
      <%= f.select :sizes, ['XS','S', 'M', 'L'. 'XL'], class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/gor_clothing/edit.js.erb
var el = $('#main-content');

el.html('');
el.html("<%= escape_javascript(render('gor_clothing/edit'))%>");

app/views/gor_clothing/index.html.erb
<% content_for :head do %>
     <%= javascript_include_tag 'admin/admin' %>
     <%= javascript_include_tag 'prototype' %>
     <%= javascript_include_tag 'scriptaculous' %>
<%end%>
<div class = 'merchandise_nav'>
	<% if current_user.gender == :male %>
		<%= link_to 'Next', @gor_clothing_next, remote: true, id: 'next_piece' %>
		<%= link_to 'Previous', @gor_clothing_previous, remote: true, id: 'previous_piece' %>
	<%end%>
	<% if current_user.gender == :female %>
		<%= link_to 'Next', @gor_clothing_next, remote: true, id: 'next_piece' %>
		<%= link_to 'Previous', @gor_clothing_previous, remote: true, id: 'previous_piece' %>
	<%end%>
</div>
<section id = 'main-content'></section>

app/views/gor_clothing/index.js.erb
var el = $('#main-content');

<% if @gor_clothing_next.any? %>
 $('#next_piece').on('click', function(){
 	el.html('');
 	el.html("<%= @gor_clothing_next.limit(1)%>");
});
 <%else%>
el.find('#next_piece').html('');
<%end%>

<% if @gor_clothing_previous.any? %>
 $('previous_piece').on('click', function(){
 	el.html('');
 	el.html("<%= @gor_clothing_previous.limit(1)%>");
 });
 <%else%>
 el.find('#previous_piece').html('');
 <%end%>

app/views/gor_clothing/new.html.erb
<%= form_for @GorClothing, html: {multipart: true} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class = "field" >
	<%= f.label :name %>
	<%= f.text_field :name %>
    <div>
    <div class = "field">
	<%= f.label :description %>
	<%= f.text_area :description %>
    </div>
    <div class = "field">
	<%= f.label :quantity %>
	<%= f.text_field :quantity%>
    </div>
    <div class = "field">
	<%= f.label :price %>
	<%= f.text_field :price%>
    </div>
    <div class = "field">
	<%= f.label :gender %>
	<%= f.select(:gender, options_for_select([['M', male]['F', female]['A', androgynous]])) %>
    </div>
    <div class = "field">
	<%= f.label :size %>
	<%= f.select(:size, options_for_select([['S', small]['M', medium]['L', large]])) %>
    </div>
    <%= f.fields_for :image do |i| %>
	<span class = "picture">
		<%= i.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
	</span>
    <%end%>
<%end%>

app/views/gor_clothing/new.js.erb
$('admin').html("<%= 'escape_javascript(render('gor_clothing/_new_piece'))' %>");

<% if @gor_clothing.attribute_present?(:description, :size, :gender, :price, :quantity, :picture) %>
	<%= @gor_clothing.build(gor_clothing_params) %>
	<%= image_preview %>
<%end%>