config/routes.rb
 Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'event_tickets_api/create'

  # get 'event_tickets_api/update'

  root 		'application#root'
  # 'sessions#new'
  
  get '/help', to: 'gor_main#help'
  get '/contact', to: 'gor_main#contact'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/soundcloud/connect' => 'soundcloud#connect'

  get '/soundcloud/callback' => 'soundcloud#connected'

  get '/logout', to: 'soundcloud#destroy'

  # get '/sessions/:page' => "sessions#show"
  get '/edit', to: 'users#edit'

  # get '/soundcloud/oauth-callback', to: 'sessions#omniauth_create'


   resources :users, except: [:index] do
   	resources :wardrobes
   	resources :playlist, except: [:index, :show]
   end

   resource :playlist do
   	member do
	   	patch 'change_up' #Randomize what gets played while keeping kept_songs in the playlist
	end

   	resources :songs, except: [:edit, :update] do
   		member do
   			post 'keep_song'
   		end
   	end
   end

  resources :preferences, only: [:index, :create, :destroy]

  resources :wardrobes, only: [:update, :index, :destroy, :detail]

  resources :gor_clothing, except: [:new] do
  	member do
  		resources :images, only: [:index, :show, :preview]
  	end
  end

  resources :possible_matches, only: [:show, :detail] do
  	member do
  		get :visible_gor_clothing, to: :show
  	end
  end

  get ':performer_name', to: 'event_tickets#artist_events', as: :artist_events

  resources :event_tickets, only: [:index, :show] do
  	 collection do
  	 	get ':input' => 'event_tickets#search', as: :search
  	 end
  end

  namespace :admin do

  	resources :gor_clothing, except: [:show] do
  		post :preview, on: :new
  		member do
  			get '/', to: :detail
  			resources :possible_matches do
  				match :destroy, to: 'possible_matches#destroy', via: [:delete], on: :collection
  			end
  			resources :images, except: [:edit, :update] do
  				match :edit_some, to: 'images#edit_some', via: [:get], on: :collection
  				match :destroy, to: 'images#destroy', via: [:delete], on: :collection
  				get :preview, on: :new
  			end
  		end
  	end

  	#image upload --> new --> triggered by carrier_wave uploader--> preview action --> render admin_gor_clothing_image_path alert(is show picture ok?)
  	#save image --> create --> 
  	

  	resources :users do
  		get 'saved_wardrobes'
  		member do
			resources :playlists, only: [:create, :destroy, :show, :index]
  		end
	end

  end


end

app/models/image.rb
class Image < ActiveRecord::Base
	enum type_of_image: [:front_shot, :show_picture, :back_shot, :model_shot]

	mount_uploader :picture, PictureUploader
	
	belongs_to :gor_clothing, foreign_key: "gor_clothing_id"
	
	validates :type_of_image, presence: true
	validates :gor_clothing_id, presence: true
	validates_presence_of :picture #a show_picture 
	# errors -> show_picture, "There must be a show_picture"

	validate :picture_size
	validate :check_for_existing_image_type
	validate :show_picture_present, on: :destroy

	private

		def show_picture_present
			errors.add(:gor_clothing_name, "needs a show picture") if self.type_of_image == :show_picture
		end

		def picture_size
			if self.picture.size > 5.megabytes
        				errors.add(:picture, "should be less than 5MB")
      			end
		end

		def check_for_existing_image_type
			errors.add(:type_of_image, "A %{type_of_image} image is present already. Would you like to override?") if self.gor_clothing_id.include?(images.where(type_of_image: params[:type_of_image]))
		end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	respond_to :js
	before_action :admin, only: [:edit_some, :preview, :new, :create, :destroy]
	before_action :find_clothing, only: [:index, :show, :edit_some, :destroy, :preview]

	layout 'final_preparation', only: [:preview]


	def new
		@image = Image.new
	end

	def show
		@image = @gor_clothing.Images.where(type_of_image: :show_picture)
	end
	
	def index
		@images = @gor_clothing.Images.all
	end

	def edit_some
		@images = @gor_clothing.Images.all
		respond_with(@gor_clothing, @images, :location => admin_gor_clothing_index_path)
	end

	def destroy
	 	@images = Image.where(:type_of_image => params[:collateral_images]) #identify which images have setForDeletion
		if params[:collateral_images].nil
			@images = @gor_clothing.Images.all	
			render admin_gor_clothing_index_path
		else
		  	@images.destroy
		  	respond_with(@gor_clothing, action: :edit_some) #gor_clothing should refer to gor_clothing/detail
		end
	end

	def preview #show form through js
	end

	private

		def Image_params
			params.require(:Image).permit(:type_of_image, :picture)
		end
		
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_images.html.erb
<% content_for :head do %>
     <%= javascript_include_tag 'admin' %>
     <%= javascript_include_tag 'prototype' %>
     <%= javascript_include_tag 'scriptaculous' %>
<%end%>
<div class = "images">
	<div class = "validation-error"></div>
	<span id="gor_clothing_<%=gor_clothing.id%>_show_picture">
		<% image_tag @gor_clothing.images.picture.show_picture if image.picture.show_picture? %>
	</span>
	<% for image in @gor_clothing.images unless @gor_clothing.images.type_of_image == "show_picture" %>
	<span class = "collateral_images">
		<span id = "images_<%= image.type_of_image %>">
			<%= image_tag image.picture.url if image.picture? %>
		</span>
	</span>
	<%end%>
	<span class = "image_update">
		<span class = 'finish_image_update'></span>
		<%= link_to 'Edit', edit_some_admin_images_path(@gor_clothing), remote: true, data: {type: :json}, id: 'edit_some_images' %> |
		<%= link_to 'Add New', new_admin_image_path, remote: true, data: {type: :json}, id: 'new_admin_piece' %>
	</span>
</div>

app/views/images/_images_finish_edit.html.erb
<%= link_to 'Finish Editing', admin_images_path(@images), method: "delete", :remote => true, :data => {confirm => "Are you sure you want to delete these?"}, id: 'finish_image_edit' %>

app/views/images/_index.html.erb
<% content_for :head do %>
     <%= javascript_include_tag '/admin/admin' %>
     <%= javascript_include_tag 'prototype' %>
     <%= javascript_include_tag 'scriptaculous' %>
<%end%>
<div class = "images">
	<div class = "validation-error"></div>
	<span id="gor_clothing_<%=gor_clothing.id%>_show_picture">
		<% image_tag @gor_clothing.images.picture.show_picture if image.picture.show_picture? %>
	</span>
	<% for image in @gor_clothing.images unless @gor_clothing.images.type_of_image == "show_picture" %>
	<span class = "collateral_images">
		<span id = "images_<%= image.type_of_image %>">
			<%= image_tag image.picture.url if image.picture? %>
		</span>
	</span>
	<%end%>
	<span class = "image_update">
		<span class = 'finish_image_update'></span>
		<%= link_to 'Edit', edit_some_admin_images_path(@gor_clothing), remote: true, data: {type: :js}, id: 'edit_some_images' %> |
		<%= link_to 'Add New', new_admin_image_path, remote: true, data: {type: :js}, id: 'new_admin_piece' %>
	</span>
</div>
 

app/views/images/destroy.html.erb
<i class="icon-destroy-link"></i>

app/views/images/edit_images.js.erb
$finish_image_edit = $('image_update').find('#finish_image_edit');
$finish_image_update = $('.image_update').find('.finish_image_update');

$(document).ready(function(){

	$('#edit_some_images').on('click', function(e){
		append_destroy_links('#edit_some_images', '#images');
		if ($finish_image_update.html('')){
			$finish_image_update.html("<%= escape_javascript(render('images/_images_finish_edit'))%>" + " | ");
		}	
	});

	$('i.icon-destroy-link').on('click', function(e){
		$(this).addClass('set-for-deletion');
	});

	$finish_image_edit.on('click', deleteGORImagesSetForDeletion(), function(){
		finish_image_update.remove();
	});
});

var deleteGORImagesSetForDeletion = function(){
	$.ajax(beforeSend: function(xhr, settings) {
    		if ( settings.dataType == undefined ) {
        			xhr.setRequestHeader("*/*;q=0.5, text/javascript", "application/javascript");
    		}
    			return fire(element, 'ajax:beforeSend', xhr);
		},{
		type: 'DELETE',
		url: '/admin/gor_clothing/:id/images',
		data: {
			destroy_link_icons: document.getElementsByClassName('icon-destroy-link'),
			collateral_images: $('i.set-for-deletion').siblings('#images_<%= image.type_of_image %>'),
			collateral_images_parent: $('.collateral_images').has('i').hasClass('set-for-deletion') //All Elements with ClassName collateral-images and set-for-deletion
		},
		context: collateral_images_parent,
		// binding.pry,
		success: function(evt, data, status, xhr){
				new Effect.Parallel([
    					new Effect.Move($(this), { sync: true, x: 400, y: 0, mode: 'relative' }),
    					new Effect.Opacity($(this), { sync: true, from: 1, to: 0 })
  				],{
    					duration: 1.5
  				});
			$(this).remove();
		}
	});
};

app/views/images/edit_some.html.erb
<%= form_tag admin_images_path do %>
	<% @gor_clothing.images.each do |image| %>
	<span class = "collateral_images_path"%>
		<span id = "images_<%= image.type_of_image %>">
			<%= image_tag image.picture.url if image.picture? %>
		</span>
	</span>
	<%end%>
<%end%>

app/views/images/edit_some.js.erb
$finish_image_edit = $('image_update').find('#finish_image_edit');
$finish_image_update = $('.image_update').find('.finish_image_update');

$(document).ready(function(){

	$('#edit_some_images').on('click', function(e){
		append_destroy_links('#edit_some_images', '#images');
		if ($finish_image_update.html('')){
			$finish_image_update.html("<%= escape_javascript(render('images/_images_finish_edit'))%>" + " | ");
		}	
	});

	$('i.icon-destroy-link').on('click', function(e){
		$(this).addClass('set-for-deletion');
	});

	$finish_image_edit.on('click', deleteGORImagesSetForDeletion(), function(){
		finish_image_update.remove();
	});
		
});

var deleteGORImagesSetForDeletion = function(){
	$.ajax(beforeSend: function(xhr, settings) {
    		if ( settings.dataType == undefined ) {
        			xhr.setRequestHeader("*/*;q=0.5, text/javascript", "application/javascript");
    		}
    			return fire(element, 'ajax:beforeSend', xhr);
		},{
		type: 'DELETE',
		url: '/admin/gor_clothing/:id/images',
		data: {
			destroy_link_icons: document.getElementsByClassName('icon-destroy-link'),
			collateral_images: $('i.set-for-deletion').siblings('#images_<%= image.type_of_image %>'),
			collateral_images_parent: $('.collateral_images').has('i').hasClass('set-for-deletion') //All Elements with ClassName collateral-images and set-for-deletion
		},
		context: collateral_images_parent,
		success: function(evt, data, status, xhr){
				new Effect.Parallel([
    					new Effect.Move($(this), { sync: true, x: 400, y: 0, mode: 'relative' }),
    					new Effect.Opacity($(this), { sync: true, from: 1, to: 0 })
  				],{
    					duration: 1.5
  				});
			$(this).remove();
		}
	});
};

app/views/images/new_preview.html.erb
<%= form_for @gor_clothing, url: [action: "create"], html: {class: "preview_form"} do |f| %>
 	<%= f.fields_for :image do |i| %
		<% div class = "image_options"%>
		   <%= i.radio_button :type_of_image, 'show_picture' %>
		   <%= i.label :type_of_image, "Show Picture" :value => 'show_picture' %>
		   <%= i.radio_button :type_of_image, "front_shot" %>
		   <%= i.label :type_of_image, "Front Shot" :value => 'front_shot' %>
		   <%= i.radio_button :type_of_image, "back_shot" %>
		   <%= i.label :type_of_image, "Back Shot" :value => 'back_shot' %>
		   <%= i.radio_button :type_of_image, "model_shot" %>
		   <%= i.label :type_of_image, "Model Shot" :value => 'model_shot' %>
		<%div%>
		<span class = "content">
		    <%= image_tag %> <!-- i.picture.url if i.picture? -->
		</span>
		<%= render 'shared/error_messages', object: i.object %>
	<%end%>
	<%= f.submit "Create" %>
<%end%>

app/views/images/preview.html.erb
<%= form_for @gor_clothing, url: [action: "create"], html: {class: "preview_form"} do |f| %>
 	<%= f.fields_for :image do |i| %
		<% div class = "image_options"%>
		   <%= i.radio_button :type_of_image, 'show_picture' %>
		   <%= i.label :type_of_image, "Show Picture" :value => 'show_picture' %>
		   <%= i.radio_button :type_of_image, "front_shot" %>
		   <%= i.label :type_of_image, "Front Shot" :value => 'front_shot' %>
		   <%= i.radio_button :type_of_image, "back_shot" %>
		   <%= i.label :type_of_image, "Back Shot" :value => 'back_shot' %>
		   <%= i.radio_button :type_of_image, "model_shot" %>
		   <%= i.label :type_of_image, "Model Shot" :value => 'model_shot' %>
		<%div%>
		<span class = "content">
		    <%= image_tag i.picture.url if i.picture? %>
		</span>
		<%= render 'shared/error_messages', object: i.object %>
	<%end%>
	<%= f.submit "Create" %>
<%end%>

app/views/images/preview.js.erb
var FormEl = $('.potential_piece_box');

FormEl.html('');
FormEl.html("<%= escape_javascript(render('images/new_preview'))%>");


previewFile('ImagePreview');