config/routes.rb
 Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'event_tickets_api/create'

  # get 'event_tickets_api/update'

  root 		'application#root'
  # 'sessions#new'
  
  get '/help', to: 'gor_main#help'
  get '/contact', to: 'gor_main#contact'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/soundcloud/connect' => 'soundcloud#connect'

  get '/soundcloud/callback' => 'soundcloud#connected'

  get '/logout', to: 'soundcloud#destroy'

  # get '/sessions/:page' => "sessions#show"
  get '/edit', to: 'users#edit'

  # get '/soundcloud/oauth-callback', to: 'sessions#omniauth_create'


   resources :users, except: [:index] do
   	resources :wardrobes
   	resources :playlist, except: [:index, :show]
   end

   resource :playlist do
   	member do
	   	patch 'change_up' #Randomize what gets played while keeping kept_songs in the playlist
	end

   	resources :songs, except: [:edit, :update] do
   		member do
   			post 'keep_song'
   		end
   	end
   end

  resources :preferences, only: [:index, :create, :destroy]

  resources :wardrobes, only: [:update, :index, :destroy, :detail]

  resources :gor_clothing, except: [:new] do
  	member do
  		resources :images, only: [:index, :show, :preview]
  	end
  end

  resources :possible_matches, only: [:show, :detail] do
  	member do
  		get :visible_gor_clothing, to: :show
  	end
  end

  get ':performer_name', to: 'event_tickets#artist_events', as: :artist_events

  resources :event_tickets, only: [:index, :show] do
  	 collection do
  	 	get ':input' => 'event_tickets#search', as: :search
  	 end
  end

  namespace :admin do

  	resources :gor_clothing, except: [:show] do
  		post :preview, on: :new
  		member do
  			get '/', to: :detail
  			resources :possible_matches do
  				match :destroy, to: 'possible_matches#destroy', via: [:delete], on: :collection
  			end
  			resources :images, except: [:edit, :update] do
  				match :edit_some, to: 'images#edit_some', via: [:get], on: :collection
  				match :destroy, to: 'images#destroy', via: [:delete], on: :collection
  				get :preview, on: :new
  			end
  		end
  	end

  	#image upload --> new --> triggered by carrier_wave uploader--> preview action --> render admin_gor_clothing_image_path alert(is show picture ok?)
  	#save image --> create --> 
  	

  	resources :users do
  		get 'saved_wardrobes'
  		member do
			resources :playlists, only: [:create, :destroy, :show, :index]
  		end
	end

  end


end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <li><%= link_to "GodsOfRiotry", root_path %></li>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin_detail.html.erb
<% if current_user?(admin) %>
	<% render :file => 'layouts/admin_detail' %>
	<% content_for :detail do %>
		<% yield(:final_preparation) or yield %>
	<% end %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= yield(:title) %>| GodsOfRiotry </title>
  <title><%= content_for?(:title) ? yield(:title) : 'GodsOfRiotry' %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= include_gon(watch: true) %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div class="col-md-6 col-md-offset-3">
	<% if notice %>
		<p class ="alert alert-success"><%=notice%></p>
	<%end%>
	<% if alert %>
		<p class ="alert alert-danger"><%= alert %></p>
	<%end%>
</div>
<%= content_for?(:main) ? yield(:main) : yield %>
</body>
</html>

app/views/layouts/event_tickets.html.erb
<% content_for :event_tickets %>
	<%= 'shared/_error_messages' %>
	<%= yield %>
<% end %>
<%= render template: "layouts/main_display" %>

app/views/layouts/final_preparation.html.erb
<head>	
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'final_preparation' %>
</head>
<% content_for :final_preparation do %>
<div id = 'final_preparation'>
	<div class = 'potential_piece_box'>
		<% yield %>
	</div>
</div>
<% end %>
<% if current_user?(user) %>
	<% render :file => 'layouts/detail' %>
<% end %>

app/views/layouts/main_display.html.erb
<% content_for :main do %>
	<div class = 'main'>
		<header>
			<nav class="main-nav">
				<ul>
					<li><%= link_to 'Sign In', login_path, class: "cd-signin" %></li>
					<li><%= link_to 'Sign Up', new_user_path, class: "cd-signup" %></li>
				</ul>
			</nav>
		</header>
		<section class = 'Intro'>,
		</section>
		<section class = "Songs">
		</section>
		<section class = 'two_column'>
		<%= yield(:wardrobe) %>
		<%= yield(:possible_matches) %>
		</section>
		<section class = "FunTimes">
		<%= yield(:event_tickets) %>
		</section>
	</div>
<%end%>
<%= render template: "layouts/application" %>

app/views/layouts/possible_matches.html.erb
<%= content_for :possible_matches do %>
	<%= 'shared/_error_messages' %>
	<%= yield %>
<%end%>
<%= render template: "layouts/main_display" %>

app/views/layouts/wardrobe.html.erb
<%= content_for :wardrobe %>
	<%= 'shared/_error_messages' %>
	<%= yield %>
<%end%>
<%= render template: "layouts/main_display" %>